name: Create Installer

on:
  push:
    branches:
      - master

env:
  APP_NAME: "Zacks Outlining Tool"
  APP_VERSION: "1.0.0"
  PRODUCT_NAME: "Zacks Outlining Tool"
  INSTALLER_NAME: "${PRODUCT_NAME}-${APP_VERSION}-setup.exe"

jobs:
  build_installer:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install WiX Toolset
      run: |
        choco install wixtoolset
        refreshenv

    - name: Build installer
      run: |
        candle -ext WixNetFxExtension -arch x64 -dAppVersion=${APP_VERSION} -dProductName="${APP_NAME}" Product.wxs
        light -ext WixNetFxExtension -sval -sice:ICE60 -sice:ICE64 -sice:ICE91 -sice:ICE97 -sice:ICE80 -sice:ICE53 -sice:ICE43 -out ${INSTALLER_NAME} Product.wixobj

    - name: Upload installer as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${INSTALLER_NAME}
        path: ${INSTALLER_NAME}
