name: Create Installer

on:
  push:
    branches:
      - master

env:
  APP_NAME: "Zacks Outlining Tool"
  APP_VERSION: "1.0.0"
  PRODUCT_NAME: "Zacks Outlining Tool"
  INSTALLER_NAME: "${PRODUCT_NAME}-${APP_VERSION}-setup.exe"

jobs:
  build_installer:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Inno Setup
      run: |
        choco install innosetup
        refreshenv
        
    - name: Verify Inno Setup installation
      run: iscc.exe /?

    - name: Build installer
      run: iscc.exe Product.iss

    - name: Upload installer as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${INSTALLER_NAME}
        path: ${INSTALLER_NAME}
