name: Create Deployment Package

on:
  push:
    branches:
      - Master

env:
  APP_NAME: "Zacks Outlining Tool"
  APP_VERSION: "1.0.1"
  DOTNET_VERSION: 7.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .Net SDK path
      uses: actions/setup-dotnet@v1

    - name: NuGet restore
      run: dotnet restore "${{ env.APP_NAME }}.sln"

    - name: Build solution
      run: dotnet build "${{ env.APP_NAME }}.sln" --configuration Release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APP_VERSION: ${{ env.APP_VERSION }}
      with:
        tag_name: v${{ env.APP_VERSION }}
        release_name: Release v${{ env.APP_VERSION }}
        draft: false
        prerelease: false
        
    - name: Create Zip File
      run: 7z a -tzip "${{ env.APP_NAME }}_${{ env.APP_VERSION }}.zip" "./${{ env.APP_NAME }}/bin/Release/*.*"

    - name: Upload Release Asset - Zip
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./${{ env.APP_NAME }}_${{ env.APP_VERSION }}.zip"
        asset_name: "${{ env.APP_NAME }}_${{ env.APP_VERSION }}.zip"
        asset_content_type: application/zip
