name: Build and Package Installer
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Framework 4.8.1
        uses: microsoft/setup-dotnet@v1.7.2
        with:
          dotnet-version: '4.8.1'

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build project
        run: msbuild /p:Configuration=Release /t:Rebuild

      - name: Package installer
        uses: jquintozamora/action-download-artifact@v2.1.1
        with:
          name: Installer
          repo: ${{ github.repository }}
          ref: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: Installer.yml
          path: ./installer

      - name: Create installer
        run: ./installer/setup.exe /S
