name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build project
      run: msbuild /p:Configuration=Release /t:Rebuild

    - name: Publish project
      run: |
        cd bin\Release
        csc /out:ZacksOutliningTool.exe ZacksOutliningTool.cs
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ZacksOutliningTool
        path: bin\Release\ZacksOutliningTool.exe